### PR TITLE
Added tweet transition, modified the js a bit and improved the UI even further. Closes #14

### LINKED ISSUE #14: Displaying Tweets
The white space background doesn't cover the tweets sometimes.
![screenshot(https://cloud.githubusercontent.com/assets/12889549/12216027/99516fa8-b6fa-11e5-9f36-4235aa68ee97.png)

Reference to commit #13

### PR DESCRIPTION
**Pull request by yasoob**
All the commits contain different features. We should not squash them so that if someone wants to revert a specific modification he can easily do so :smile: 

Modifications:
- [x] Closed #14 
- [x] Tweets change after 6.6 seconds (Enough time to read the tweet) Solves the first issue in #9
- [x] Added a "fork me on GitHub" button
- [x] Added a nice arrow above the `tweets` div

### CODE REVIEW

**Comment by yasoob** [comment]
Rebase totally detroyed the pull request. Let me open a new one. :disappointed:

**Comment by yasoob** [comment]
@mariobehling Let me know if these updates are good to merge. The final result can be seen [here](http://yasoob.me/fossasia-loklak-webtweets/). I hope you will approve [my task](https://codein.withgoogle.com/dashboard/task-instances/5670899655114752/?sp-page=1). I will continue modifying this website. :smile: :+1:

**Comment by anshuman73** [comment]
Hi, I've noticed a small bug while using the demo on your repo. When someone clicks the next tweet button, the timeout isn't refreshed, thus if I clicked next tweet couple of times to go ahead, it sometimes happens  I don't get to see the tweet because the timeout changes it at that point of time

**Comment by yasoob** [comment]
@anshuman73 Nice catch! Let me update the code

**Comment by anshuman73** [comment]
:) Happy to help. After all we all are collaborating to build something awesome !

**Comment by yasoob** [comment]
Done!

**Comment by mariobehling** [comment]
Great job! Thank you!

**Comment by mariobehling** [comment]
Please check, what you would like to do next, e.g. offer option in html code like
- show the last x number of tweets
- limit search results to accounts, search terms etc.

**Comment by yasoob** [comment]
Thanks to you. Your reply on the task pumped me :+1: fossasia couldn't have got better mentors than you guys! Will the GCI task get approved only after doing the above mentioned tasks? Or can I do the above mentioned tasks _after_ the GCI task approval? :smile:

**Pull request merged**
