### PR TITLE
added custom configuration modal. Click on twitter logo to activate it.

### PR DESCRIPTION
**Pull request by yasoob**
:heart: Let me know if this is fine :smile: 

[Preview](http://yasoob.me/fossasia-loklak-webtweets)

### CODE REVIEW

**Comment by yasoob** [comment]
screenshot from 2016-01-18 23 40 09

**Comment by mariobehling** [comment]
Very cool idea, but not exactly the goal to let the user change the tweets of our site, right? However this could be a nice feature for other site. Could we modularize it e.g. "add this code to get this feature" and document it in the Readme.md?

**Comment by yasoob** [comment]
Well........This is a client-side modification (It will not globally affect your website) so IMO this should be fine without any further modularization. We can not easily modularize it because it depends on all the other `.js` files as well. I hope this clarifies the issue :smile: What do you suggest?

**Comment by yasoob** [comment]
Hey @mariobehling Kindly approve [this](https://codein.withgoogle.com/dashboard/task-instances/5758338994274304/?sp-page=1) task soon so that I can work on [this](https://codein.withgoogle.com/tasks/5470699464425472/?sp-is_beginner=False) followup task :+1:

**Comment by yasoob** [comment]
Hey @sudheesh001 @Orbiter can you guys kindly check this PR and approve [this](https://codein.withgoogle.com/dashboard/task-instances/5758338994274304/?sp-page=1) task? :smile:

**Comment by mariobehling** [comment]
Hi @yasoob could you please comment this option out and add the info how to switch it on into the readme.md? Actually this is a nice feature, but may not be wanted in some websites. Thank you!

**Comment by yasoob** [comment]
@mariobehling As you say :smile: Let me get back to you with a PR

**Comment by yasoob** [comment]
Hey @mariobehling I have updated this PR with a new updated commit. Can you kindly take a look? :+1:

**Pull request merged**
