### PR TITLE
Remove twitter fetcher dependency, add AngularJS and loklak.org support.

### PR DESCRIPTION
**Pull request by DengYiping**
GCI task

### CODE REVIEW

**Comment by sudheesh001** [comment]
Could you please fix this ?
screen shot 2016-01-06 at 2 26 38 pm

**Comment by DengYiping** [comment]
Hello @sudheesh001 . `search.json?q=#fossasia` seems to be a invalid queries for server. (I look at the api doc and find out it should be valid, but I'm not sure what part of loklak-server cause the problem.) `http://loklak.org/api/search.json?q=#America` is a example: you do not get any result, and  `http://loklak.org/api/search.json?q=#fossasia` is the same. Most likely it is a problem in `loklak_server`. I just use`fossasia` instead of `#fossasia` in those queries. Please check again, and I will file a problem in loklak_server.

**Comment by DengYiping** [comment]
@sudheesh001 One possible solution is add the same key word as the hashtag in queries, like `http://loklak.org/api/search.json?q= fossasia #fossasia`. I'm sure it is a problem in loklak_server.

**Comment by mariobehling** [comment]
Hi, I am merging this PR even though it is work in progress. Goal is, that different students can work on the same code. Cheers.

**Pull request merged**
